### ISSUE TITLE
The capacity of Map

### ISSUE THREAD

**Issue by tx0619s** [barrylyung/a1p2#3]
Hi Could we have capacity in addition to size in Class Map?

**Comment by Xiaocheng-Zhang** [comment]
And can we use the standard object & string classes described on piazza? https://piazza.com/class/k51bluky59n2jr?cid=166

**Comment by Xiaocheng-Zhang** [comment]
Or whatever classes we want if it suitable for all tests.

**Comment by barrylyung** [comment]
@tx0619s I have added size_t capacity_ to the map class.
@Xiaocheng-Zhang We will be replacing our classes with the piazza classes today

**Comment by NickSimmons97** [comment]
@Xiaocheng-Zhang we have replaced our string.h and object.h classes with the most popular piazza implementation- https://piazza.com/class/k51bluky59n2jr?cid=345
