### ISSUE TITLE
Object field in node

### ISSUE THREAD

**Issue by Xiaocheng-Zhang** [barrylyung/a1p2#4]
I thought we need both key and value in node.h as Object*.

**Comment by Xiaocheng-Zhang** [comment]
Besides, standard hashmap is a 2d array of nodes, would you allow us to change or just follow your constructor? It is ok to use 1d array to implement a hashmap.

**Comment by barrylyung** [comment]
Changed the key and value to Object* in node.h. We believe a 1D array of node (with key-value pair) is the implementation for the hash map. How would a 2D Array be used instead?

**Comment by Xiaocheng-Zhang** [comment]
2d array is a common design dealt with hashed index conflicts, when there is exist same index after computing the hash code, put the node as next element after the existed node.
1d array will put the conflict node on the next element.

**Comment by Xiaocheng-Zhang** [comment]
I have used 1D array. That's fine.

**Comment by Xiaocheng-Zhang** [comment]
You might need to add tests in test-map.cpp, it is incomplete. Did you push the wrong test file? Besides, I think you might want get method return Object* instead of void.

**Comment by barrylyung** [comment]
@Xiaocheng-Zhang I have pushed the new test-map. Keeping void return because it should exit if it fails. I don't think it needs to return anything for a test function

**Comment by Xiaocheng-Zhang** [comment]
Your getValue method in map.h return type is void. I mean this you might want it be Object. Besides, your addElement method has implemented. Would you want us to rewrite it?
